// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0
// source: proxy.proto

package proxygrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxService_ResumeSandbox_FullMethodName = "/proxy.SandboxService/ResumeSandbox"
)

// SandboxServiceClient is the client API for SandboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SandboxService is used by the client-proxy to resume sandboxes.
type SandboxServiceClient interface {
	ResumeSandbox(ctx context.Context, in *SandboxResumeRequest, opts ...grpc.CallOption) (*SandboxResumeResponse, error)
}

type sandboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxServiceClient(cc grpc.ClientConnInterface) SandboxServiceClient {
	return &sandboxServiceClient{cc}
}

func (c *sandboxServiceClient) ResumeSandbox(ctx context.Context, in *SandboxResumeRequest, opts ...grpc.CallOption) (*SandboxResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxResumeResponse)
	err := c.cc.Invoke(ctx, SandboxService_ResumeSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxServiceServer is the server API for SandboxService service.
// All implementations must embed UnimplementedSandboxServiceServer
// for forward compatibility.
//
// SandboxService is used by the client-proxy to resume sandboxes.
type SandboxServiceServer interface {
	ResumeSandbox(context.Context, *SandboxResumeRequest) (*SandboxResumeResponse, error)
	mustEmbedUnimplementedSandboxServiceServer()
}

// UnimplementedSandboxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxServiceServer struct{}

func (UnimplementedSandboxServiceServer) ResumeSandbox(context.Context, *SandboxResumeRequest) (*SandboxResumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeSandbox not implemented")
}
func (UnimplementedSandboxServiceServer) mustEmbedUnimplementedSandboxServiceServer() {}
func (UnimplementedSandboxServiceServer) testEmbeddedByValue()                        {}

// UnsafeSandboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxServiceServer will
// result in compilation errors.
type UnsafeSandboxServiceServer interface {
	mustEmbedUnimplementedSandboxServiceServer()
}

func RegisterSandboxServiceServer(s grpc.ServiceRegistrar, srv SandboxServiceServer) {
	// If the following call panics, it indicates UnimplementedSandboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxService_ServiceDesc, srv)
}

func _SandboxService_ResumeSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ResumeSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ResumeSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ResumeSandbox(ctx, req.(*SandboxResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxService_ServiceDesc is the grpc.ServiceDesc for SandboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxy.SandboxService",
	HandlerType: (*SandboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResumeSandbox",
			Handler:    _SandboxService_ResumeSandbox_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proxy.proto",
}

const (
	CapacityService_GetCapacitySnapshot_FullMethodName   = "/proxy.CapacityService/GetCapacitySnapshot"
	CapacityService_ListScaleInCandidates_FullMethodName = "/proxy.CapacityService/ListScaleInCandidates"
	CapacityService_BeginWorkerScaleIn_FullMethodName    = "/proxy.CapacityService/BeginWorkerScaleIn"
	CapacityService_VerifyWorkerScaleIn_FullMethodName   = "/proxy.CapacityService/VerifyWorkerScaleIn"
	CapacityService_CancelWorkerScaleIn_FullMethodName   = "/proxy.CapacityService/CancelWorkerScaleIn"
)

// CapacityServiceClient is the client API for CapacityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CapacityService exposes the minimum private contract required for node
// scale-out reconciliation.
type CapacityServiceClient interface {
	GetCapacitySnapshot(ctx context.Context, in *CapacitySnapshotRequest, opts ...grpc.CallOption) (*CapacitySnapshotResponse, error)
	ListScaleInCandidates(ctx context.Context, in *ListScaleInCandidatesRequest, opts ...grpc.CallOption) (*ListScaleInCandidatesResponse, error)
	BeginWorkerScaleIn(ctx context.Context, in *WorkerScaleInRequest, opts ...grpc.CallOption) (*WorkerScaleInState, error)
	VerifyWorkerScaleIn(ctx context.Context, in *WorkerScaleInRequest, opts ...grpc.CallOption) (*WorkerScaleInState, error)
	CancelWorkerScaleIn(ctx context.Context, in *WorkerScaleInRequest, opts ...grpc.CallOption) (*WorkerScaleInState, error)
}

type capacityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCapacityServiceClient(cc grpc.ClientConnInterface) CapacityServiceClient {
	return &capacityServiceClient{cc}
}

func (c *capacityServiceClient) GetCapacitySnapshot(ctx context.Context, in *CapacitySnapshotRequest, opts ...grpc.CallOption) (*CapacitySnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapacitySnapshotResponse)
	err := c.cc.Invoke(ctx, CapacityService_GetCapacitySnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capacityServiceClient) ListScaleInCandidates(ctx context.Context, in *ListScaleInCandidatesRequest, opts ...grpc.CallOption) (*ListScaleInCandidatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScaleInCandidatesResponse)
	err := c.cc.Invoke(ctx, CapacityService_ListScaleInCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capacityServiceClient) BeginWorkerScaleIn(ctx context.Context, in *WorkerScaleInRequest, opts ...grpc.CallOption) (*WorkerScaleInState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerScaleInState)
	err := c.cc.Invoke(ctx, CapacityService_BeginWorkerScaleIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capacityServiceClient) VerifyWorkerScaleIn(ctx context.Context, in *WorkerScaleInRequest, opts ...grpc.CallOption) (*WorkerScaleInState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerScaleInState)
	err := c.cc.Invoke(ctx, CapacityService_VerifyWorkerScaleIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capacityServiceClient) CancelWorkerScaleIn(ctx context.Context, in *WorkerScaleInRequest, opts ...grpc.CallOption) (*WorkerScaleInState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerScaleInState)
	err := c.cc.Invoke(ctx, CapacityService_CancelWorkerScaleIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapacityServiceServer is the server API for CapacityService service.
// All implementations must embed UnimplementedCapacityServiceServer
// for forward compatibility.
//
// CapacityService exposes the minimum private contract required for node
// scale-out reconciliation.
type CapacityServiceServer interface {
	GetCapacitySnapshot(context.Context, *CapacitySnapshotRequest) (*CapacitySnapshotResponse, error)
	ListScaleInCandidates(context.Context, *ListScaleInCandidatesRequest) (*ListScaleInCandidatesResponse, error)
	BeginWorkerScaleIn(context.Context, *WorkerScaleInRequest) (*WorkerScaleInState, error)
	VerifyWorkerScaleIn(context.Context, *WorkerScaleInRequest) (*WorkerScaleInState, error)
	CancelWorkerScaleIn(context.Context, *WorkerScaleInRequest) (*WorkerScaleInState, error)
	mustEmbedUnimplementedCapacityServiceServer()
}

// UnimplementedCapacityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapacityServiceServer struct{}

func (UnimplementedCapacityServiceServer) GetCapacitySnapshot(context.Context, *CapacitySnapshotRequest) (*CapacitySnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapacitySnapshot not implemented")
}
func (UnimplementedCapacityServiceServer) ListScaleInCandidates(context.Context, *ListScaleInCandidatesRequest) (*ListScaleInCandidatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScaleInCandidates not implemented")
}
func (UnimplementedCapacityServiceServer) BeginWorkerScaleIn(context.Context, *WorkerScaleInRequest) (*WorkerScaleInState, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginWorkerScaleIn not implemented")
}
func (UnimplementedCapacityServiceServer) VerifyWorkerScaleIn(context.Context, *WorkerScaleInRequest) (*WorkerScaleInState, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyWorkerScaleIn not implemented")
}
func (UnimplementedCapacityServiceServer) CancelWorkerScaleIn(context.Context, *WorkerScaleInRequest) (*WorkerScaleInState, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelWorkerScaleIn not implemented")
}
func (UnimplementedCapacityServiceServer) mustEmbedUnimplementedCapacityServiceServer() {}
func (UnimplementedCapacityServiceServer) testEmbeddedByValue()                         {}

// UnsafeCapacityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapacityServiceServer will
// result in compilation errors.
type UnsafeCapacityServiceServer interface {
	mustEmbedUnimplementedCapacityServiceServer()
}

func RegisterCapacityServiceServer(s grpc.ServiceRegistrar, srv CapacityServiceServer) {
	// If the following call panics, it indicates UnimplementedCapacityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CapacityService_ServiceDesc, srv)
}

func _CapacityService_GetCapacitySnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapacitySnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapacityServiceServer).GetCapacitySnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapacityService_GetCapacitySnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapacityServiceServer).GetCapacitySnapshot(ctx, req.(*CapacitySnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapacityService_ListScaleInCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScaleInCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapacityServiceServer).ListScaleInCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapacityService_ListScaleInCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapacityServiceServer).ListScaleInCandidates(ctx, req.(*ListScaleInCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapacityService_BeginWorkerScaleIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerScaleInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapacityServiceServer).BeginWorkerScaleIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapacityService_BeginWorkerScaleIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapacityServiceServer).BeginWorkerScaleIn(ctx, req.(*WorkerScaleInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapacityService_VerifyWorkerScaleIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerScaleInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapacityServiceServer).VerifyWorkerScaleIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapacityService_VerifyWorkerScaleIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapacityServiceServer).VerifyWorkerScaleIn(ctx, req.(*WorkerScaleInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapacityService_CancelWorkerScaleIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerScaleInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapacityServiceServer).CancelWorkerScaleIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapacityService_CancelWorkerScaleIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapacityServiceServer).CancelWorkerScaleIn(ctx, req.(*WorkerScaleInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CapacityService_ServiceDesc is the grpc.ServiceDesc for CapacityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CapacityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxy.CapacityService",
	HandlerType: (*CapacityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapacitySnapshot",
			Handler:    _CapacityService_GetCapacitySnapshot_Handler,
		},
		{
			MethodName: "ListScaleInCandidates",
			Handler:    _CapacityService_ListScaleInCandidates_Handler,
		},
		{
			MethodName: "BeginWorkerScaleIn",
			Handler:    _CapacityService_BeginWorkerScaleIn_Handler,
		},
		{
			MethodName: "VerifyWorkerScaleIn",
			Handler:    _CapacityService_VerifyWorkerScaleIn_Handler,
		},
		{
			MethodName: "CancelWorkerScaleIn",
			Handler:    _CapacityService_CancelWorkerScaleIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proxy.proto",
}
